Python181AXF/Python181AXF/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^axf/', include('app.urls', namespace='axf'))
]

Python181AXF/app/urls.py
from django.conf.urls import url

from app import views

urlpatterns = [
    url(r'^$', views.home, name='home'),  # 首页

    url(r'^market/$', views.market, name='marketbase'),  # 闪购超市
    url(r'^market/(?P<childid>\d+)/(?P<sortid>\d+)/$', views.market, name='market'),  # 闪购超市

    # url(r'^market/$', views.market, name='market'),

    url(r'^cart/$', views.cart, name='cart'),  # 购物车
    url(r'^mine/$', views.mine, name='mine'),  # 我的

    url(r'^login/$', views.login, name='login'),  # 登录
    url(r'^logout/$', views.logout, name='logout'),  # 退出
    url(r'^register/$', views.register, name='register'),  # 登录
    url(r'^checkemail/$', views.checkemail, name='checkemail'),  # 账号验证

    url(r'^addcart/$', views.addcart, name='addcart'),  # 添加到购物车
    url(r'^subcart/$', views.subcart, name='subcart'),  # 删减购物车
    url(r'^changecartselect/$', views.changecartselect, name='changecartselect'),  # 购物车商品选中状态
    url(r'^changecartall/$', views.changecartall, name='changecartall'),  # 全选/取消全选
    url(r'^generateorder/$', views.generateorder, name='generateorder'),    # 生成订单
    url(r'orderlist/$', views.orderlist, name='orderlist'), # 订单列表
    url(r'^orderdetail/(?P<identifier>[\d.]+)/$', views.orderdetail, name='orderdetail'),  # 订单详情



    url(r'^randomtest/$', views.randomtest, name='randomtest'), # 测试接口

    url(r'^returnurl/$', views.returnurl, name='returnurl'),    # 支付成功后，客户端的显示
    url(r'^appnotifyurl/$', views.appnotifyurl, name='appnotifyurl'), # 支付成功后，订单的处理
    url(r'^pay/$', views.pay, name='pay'),  # 支付
]

Python181AXF/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %}
        {% endblock %}
    </title>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">

    <link href="https://cdn.bootcss.com/twitter-bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static 'base/css/reset.css' %}">
    <link rel="stylesheet" href="{% static 'base/css/base.css' %}">
    {% block extcss %}
    {% endblock %}

</head>
<body>

{% block body %}
    {# 导航#}
    {% block header %}
        <header>爱鲜蜂</header>
    {% endblock %}

    {# 主体内容#}
{#    320px#}
    <div class="hidescroll">
{#        340px = 320 + 20 #}
        <div id="content">
            {% block content %}
            
            {% endblock %}
        </div>
    </div>

    {# 底部#}
    {% block footer %}
        <footer>
            <a href="{% url 'axf:home' %}" class="home">
                <div class="item">
                    <div class="img"><span></span></div>
                    <div class="name">首页</div>
                </div>
            </a>
            <a href="{% url 'axf:marketbase' %}" class="market">
                <div class="item">
                    <div class="img"><span></span></div>
                    <div class="name">闪购超市</div>
                </div>
            </a>
            <a href="{% url 'axf:cart' %}" class="cart">
                <div class="item">
                    <div class="img"><span></span></div>
                    <div class="name">购物车</div>
                </div>
            </a>
            <a href="{% url 'axf:mine' %}" class="mine">
                <div class="item">
                    <div class="img"><span></span></div>
                    <div class="name">我的</div>
                </div>
            </a>
        </footer>
    {% endblock %}
{% endblock %}

<script src="{% static 'base/js/jquery.js' %}"></script>
{#<scirpt src="{% static 'base/js/jquery.cookie.js' %}"></scirpt>#}
<script src="https://cdn.bootcss.com/jquery-cookie/1.4.1/jquery.cookie.min.js"></script>
<script src="https://cdn.bootcss.com/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
<script src="{% static 'base/js/base.js' %}"></script>
{% block extjs %}
{% endblock %}

</body>
</html>