Python181AXF/Python181AXF/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^axf/', include('app.urls', namespace='axf'))
]

Python181AXF/app/urls.py
from django.conf.urls import url

from app import views

urlpatterns = [
    url(r'^$', views.home, name='home'),  # 首页

    url(r'^market/$', views.market, name='marketbase'),  # 闪购超市
    url(r'^market/(?P<childid>\d+)/(?P<sortid>\d+)/$', views.market, name='market'),  # 闪购超市

    # url(r'^market/$', views.market, name='market'),

    url(r'^cart/$', views.cart, name='cart'),  # 购物车
    url(r'^mine/$', views.mine, name='mine'),  # 我的

    url(r'^login/$', views.login, name='login'),  # 登录
    url(r'^logout/$', views.logout, name='logout'),  # 退出
    url(r'^register/$', views.register, name='register'),  # 登录
    url(r'^checkemail/$', views.checkemail, name='checkemail'),  # 账号验证

    url(r'^addcart/$', views.addcart, name='addcart'),  # 添加到购物车
    url(r'^subcart/$', views.subcart, name='subcart'),  # 删减购物车
    url(r'^changecartselect/$', views.changecartselect, name='changecartselect'),  # 购物车商品选中状态
    url(r'^changecartall/$', views.changecartall, name='changecartall'),  # 全选/取消全选
    url(r'^generateorder/$', views.generateorder, name='generateorder'),    # 生成订单
    url(r'orderlist/$', views.orderlist, name='orderlist'), # 订单列表
    url(r'^orderdetail/(?P<identifier>[\d.]+)/$', views.orderdetail, name='orderdetail'),  # 订单详情



    url(r'^randomtest/$', views.randomtest, name='randomtest'), # 测试接口

    url(r'^returnurl/$', views.returnurl, name='returnurl'),    # 支付成功后，客户端的显示
    url(r'^appnotifyurl/$', views.appnotifyurl, name='appnotifyurl'), # 支付成功后，订单的处理
    url(r'^pay/$', views.pay, name='pay'),  # 支付
]

Python181AXF/templates/cart/cart.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}
    购物车
{% endblock %}

{% block extcss %}
    <link rel="stylesheet" href="{% static 'cart/css/cart.css' %}">
{% endblock %}
{% block extjs %}
    <script src="{% static 'cart/js/cart.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="cart">
        <ul>
            {% for cart in carts %}
                <li>
                    <div class="confirm-wrapper" data-cardid="{{ cart.id }}">
                        {% if cart.isselect %}
                            <span class="glyphicon glyphicon-ok"></span>
                        {% else %}
                            <span class="no"></span>
                        {% endif %}
                    </div>

                    <div class="content-wrapper">
                        <div class="img">
                            <img src="{{ cart.goods.productimg }}" alt="">
                        </div>
                        <div class="detail">
                            <p class="name">{{ cart.goods.productlongname }}</p>
                            <p class="price" data-price="{{ cart.goods.price }}">{{ cart.goods.price }}</p>
                            <p class="num" data-number="{{ cart.number }}">X{{ cart.number }}</p>
                        </div>
                    </div>
                </li>
            {% endfor %}
        </ul>

        <div class="bill">
            <div class="bill-left">
                <div class="all" data-all="{{ isall|lower }}">
                    {% if isall %}
                        <span class="glyphicon glyphicon-ok"></span>
                    {% else %}
                         <span class="no"></span>
                    {% endif %}
                    <b>全选</b>
                </div>
                <div class="total">
                    <span>￥</span>
                    <b>2019</b>
                </div>
            </div>

            <div class="bill-right" id="order">
                <a href="{% url 'axf:generateorder' %}">
                    下单
                </a>
            </div>
        </div>
    </div>
{% endblock %}

Python181AXF/templates/cart/no-login.html
{% extends 'base/base.html' %}

{% block content %}
    <div class="no-login">
        <a href="{% url 'axf:login' %}">
            请登录后操作
        </a>
    </div>
{% endblock %}