Python181AXF/Python181AXF/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^axf/', include('app.urls', namespace='axf'))
]

Python181AXF/app/urls.py
from django.conf.urls import url

from app import views

urlpatterns = [
    url(r'^$', views.home, name='home'),  # 首页

    url(r'^market/$', views.market, name='marketbase'),  # 闪购超市
    url(r'^market/(?P<childid>\d+)/(?P<sortid>\d+)/$', views.market, name='market'),  # 闪购超市

    # url(r'^market/$', views.market, name='market'),

    url(r'^cart/$', views.cart, name='cart'),  # 购物车
    url(r'^mine/$', views.mine, name='mine'),  # 我的

    url(r'^login/$', views.login, name='login'),  # 登录
    url(r'^logout/$', views.logout, name='logout'),  # 退出
    url(r'^register/$', views.register, name='register'),  # 登录
    url(r'^checkemail/$', views.checkemail, name='checkemail'),  # 账号验证

    url(r'^addcart/$', views.addcart, name='addcart'),  # 添加到购物车
    url(r'^subcart/$', views.subcart, name='subcart'),  # 删减购物车
    url(r'^changecartselect/$', views.changecartselect, name='changecartselect'),  # 购物车商品选中状态
    url(r'^changecartall/$', views.changecartall, name='changecartall'),  # 全选/取消全选
    url(r'^generateorder/$', views.generateorder, name='generateorder'),    # 生成订单
    url(r'orderlist/$', views.orderlist, name='orderlist'), # 订单列表
    url(r'^orderdetail/(?P<identifier>[\d.]+)/$', views.orderdetail, name='orderdetail'),  # 订单详情



    url(r'^randomtest/$', views.randomtest, name='randomtest'), # 测试接口

    url(r'^returnurl/$', views.returnurl, name='returnurl'),    # 支付成功后，客户端的显示
    url(r'^appnotifyurl/$', views.appnotifyurl, name='appnotifyurl'), # 支付成功后，订单的处理
    url(r'^pay/$', views.pay, name='pay'),  # 支付
]

Python181AXF/templates/mine/login.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}
    登录
{% endblock %}

{% block footer %}
{% endblock %}

{% block extcss %}
    <link rel="stylesheet" href="{% static 'mine/css/login.css' %}">
{% endblock %}

{% block extjs %}
    <script src="{% static 'mine/js/login.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="login">
        <div class="back">
            <a href="{% url 'axf:mine' %}">
                <span class=" glyphicon glyphicon-remove "></span>
            </a>
        </div>

        <form action="{% url 'axf:login' %}" method="post">
            {% csrf_token %}

            <div class="input-group">
                <span class="input-group-addon">邮箱</span>
                <input type="text" class="form-control" placeholder="163邮箱/QQ邮箱.." name="email" required>
            </div>
            <p style="color: red;">
                {{ user_err }}
            </p>

            <div class="input-group">
                <span class="input-group-addon">密码</span>
                <input type="password" class="form-control" placeholder="6~10位数密码" name="password" required>
            </div>
            <p style="color: red">
                {{ ps_err }}
            </p>

            <input type="submit" value="登录" id="subButton">
        </form>
    </div>
{% endblock %}

Python181AXF/templates/mine/mine.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}
    我的
{% endblock %}

{% block extcss %}
    <link rel="stylesheet" href="{% static 'mine/css/mine.css' %}">
{% endblock %}
{% block extjs %}
    <script src="{% static 'mine/js/mine.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="mine">
        <div class="user-wrapper">
            <div class="user-img">
                <img src="/static/mine/img/{{ user.img | default:"axf.png" }}" alt="">
            </div>
            <div class="user-content">
                <p>
                    <span class="glyphicon glyphicon-user"></span>
                    <a id="login-i">
                        {{ user.name | default:'未登录' }}
                    </a>
                </p>
                <p>
                    <span class="glyphicon glyphicon-th-list"></span>
                    等级: {{ user.rank | default:'无' }}
                </p>
                <a href="{% url 'axf:register' %}" class="register">注册</a>
            </div>
        </div>

        <div class="collect">
            <span class="glyphicon glyphicon-flash"></span>
            <i>商品收藏</i>
        </div>

        <div class="other">
            <section class="my">
                <span>我的订单</span>
                <a href="{% url 'axf:orderlist' %}">查看全部订单 <i class="glyphicon glyphicon-chevron-right "></i> </a>
            </section>

            <section>
                <ul>
                    <li>
                        <a href="#">
                            <dl class="item">
                                <dt>
                                    <span class="glyphicon glyphicon-gift"></span>
                                    <span class="badge">{{ waitpay }}</span>
                                </dt>
                                <dd>
                                    待付款
                                </dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <dl>
                                <dt class="item">
                                    <span class="glyphicon glyphicon-leaf"></span>
                                    <span class="badge">{{ paydone }}</span>
                                </dt>
                                <dd>待收货</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <dl>
                                <dt><span class="glyphicon glyphicon-fire"></span></dt>
                                <dd>待评价</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <dl>
                                <dt><span class="glyphicon glyphicon-plane"></span></dt>
                                <dd>退款/售后</dd>
                            </dl>
                        </a>
                    </li>
                </ul>
            </section>

            <section>
                <ul>
                    <li>
                        <a href="#">
                            <dl>
                                <dt><span class="glyphicon glyphicon-random"></span></dt>
                                <dd>优惠劵</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <dl>
                                <dt><span class="glyphicon glyphicon-comment"></span></dt>
                                <dd>收货地址</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <dl>
                                <dt><span class="glyphicon glyphicon-magnet"></span></dt>
                                <dd>客户反馈</dd>
                            </dl>
                        </a>
                    </li>
                    <li>
                        <a href="#">
                            <dl>
                                <dt><span class="glyphicon glyphicon-wrench"></span></dt>
                                <dd>关于我们</dd>
                            </dl>
                        </a>
                    </li>
                </ul>
            </section>

            {% if user %}
                <section class="quit">
                    <a href="{% url 'axf:logout' %}">
                        退出
                    </a>
            </section>
            {% endif %}
        </div>
    </div>
{% endblock %}

Python181AXF/templates/mine/register.html
{% extends 'base/base.html' %}
{% load static %}

{% block title %}
    注册
{% endblock %}

{% block footer %}
{% endblock %}

{% block extcss %}
    <link rel="stylesheet" href="{% static 'mine/css/registe.css' %}">
{% endblock %}

{% block extjs %}
    <script src="{% static 'mine/js/registerr.js' %}"></script>
{% endblock %}

{% block content %}
    <div class="register">
        <div class="back">
            <a href="{% url 'axf:mine' %}">
                <span class=" glyphicon glyphicon-remove "></span>
            </a>
        </div>

        <form action="{% url 'axf:register' %}" method="post">
            {% csrf_token %}


            <div class="form-group has-feedback" id="email">
                <div class="input-group">
                    <span class="input-group-addon">邮箱</span>


                    <input type="text" class="form-control" placeholder="163邮箱/QQ邮箱.." name="email" id="email-t"
                           data-toggle="popover" data-placement="bottom"
                           data-content="格式不正确">

                </div>
                <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
            </div>


            <div class="form-group has-feedback" id="password">
                <div class="input-group">
                    <span class="input-group-addon">密码</span>
                    <input type="password" class="form-control" placeholder="6~10位数密码" name="password">
                </div>
                <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
            </div>


            <div class="form-group has-feedback" id="password-d">
                <div class="input-group">
                    <span class="input-group-addon">确认密码</span>
                    <input type="password" class="form-control" placeholder="6~10位数密码" id="password-t"
                           tabindex="0" data-toggle="popover" data-trigger="focus" data-placement="bottom"
                           data-content="两次密码不一致">
                </div>
                <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
            </div>


            <div class="form-group has-feedback" id="name">
                <div class="input-group">
                    <span class="input-group-addon">昵称</span>
                    <input type="text" class="form-control" placeholder="3~10位数(昵称)" name="name">
                </div>
                <span class="glyphicon form-control-feedback" aria-hidden="true"></span>
            </div>

{#             submit按钮有特殊功能，提交功能#}
{#            <input type="submit" value="注册" id="subButton" disabled class="form-control">#}
        </form>

        <button id="subButton">注册</button>
    </div>
{% endblock %}